# .pre-commit-config.yaml
repos:
  # Python
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black
        language: python
        args: [--line-length=120]

  - repo: local
    hooks:
      # Non-ASCII
      - id: strip-non-ascii
        name: Strip non-ASCII / non-printable characters
        entry: python3 pre-commit/strip_non_ascii.py
        language: system
        types: [text]
        exclude: ^(build/|install/|log/|.jpg|.jpeg|.png|.bmp|.gif)$

      # C++
      - id: clang-format
        name: clang-format
        entry: clang-format -i --style=file:pre-commit/.clang-format
        language: python
        additional_dependencies:
          - clang-format==18.1.8
        files: \.(cpp|cc|h|hpp)$

      - id: capitalize-cpp-comments
        name: Capitalize C++ comments
        entry: python3 pre-commit/capitalize_cpp_comments.py
        language: system
        files: \.(cpp|cc|h|hpp)$

      # Python
      - id: capitalize-python-comments
        name: Capitalize Python comments
        entry: python3 pre-commit/capitalize_python_comments.py
        language: system
        files: \.py$

      # YAML
      - id: capitalize-yaml-comments
        name: Capitalize YAML comments
        entry: python3 pre-commit/capitalize_yaml_comments.py
        language: system
        files: \.(yaml|yml)$

      # TXT
      - id: capitalize-txt-comments
        name: Capitalize TXT first lines
        entry: python3 pre-commit/capitalize_txt_comments.py
        language: system
        files: \.txt$

      # XML
      - id: capitalize-xml-comments
        name: Capitalize XML comments
        entry: python3 pre-commit/capitalize_xml_comments.py
        language: system
        files: \.xml$

      # Markdown
      - id: capitalize-markdown-comments
        name: Capitalize Markdown HTML comments
        entry: python3 pre-commit/capitalize_md_comments.py
        language: system
        files: \.(md|markdown)$

      # License headers
      - id: license-cpp
        name: Add LICENSE header (C/C++)
        entry: python3 pre-commit/license_cpp.py
        language: system
        files: \.(c|cpp|cc|h|hpp)$

      - id: license-python
        name: Add LICENSE header (Python)
        entry: python3 pre-commit/license_python.py
        language: system
        files: \.py$
